#!/bin/bash
#SBATCH --cpus-per-task=4
module load matlab
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(1, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(2, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(3, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(4, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(5, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(6, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(7, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(8, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(9, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(10, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(11, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(12, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(13, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(14, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(15, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(16, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(17, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(18, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(19, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(20, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(21, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(22, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(23, 5); exit;"
srun matlab -nojvm -nosplash -r "compute_globalSaliency_video2img(24, 5); exit;"
